### ISSUE TITLE
python sdk websocket not work

### ISSUE THREAD

**Issue by BigXia** [okcoin-okex/open-api-v3-sdk#34]
show below after running `python3   websocket_example.py`

Traceback (most recent call last):
  File "websocket_example.py", line 152, in <module>
    asyncio.get_event_loop().run_until_complete(subscribe_without_login(url, channels))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
......
......
  raise OSError(err, 'Connect call failed %s' % (address,))
TimeoutError: [Errno 110] Connect call failed ('88.191.249.183', 10442)

**Comment by nearlai** [comment]
same issue, are waiting for a reply.

**Comment by tanshinepan** [comment]
waiting

**Comment by dabizichali** [comment]
我也遇到这个问题，已经使用影索翻墙了还是无法连接
