### ISSUE TITLE
JsonSyntaxException getCandles Java Unit Test

### ISSUE THREAD

**Issue by mdvx** [okcoin-okex/open-api-v3-sdk#59]
com/okcoin/commons/okex/open/api/test/spot/SpotProductAPITest.java

The url returns data  - https://www.okex.com/api/spot/v3/instruments/BTC-usdt/candles?granularity=60

timestamp={2019-08-17T21:45:40.876416900Z}
17:45:40.887 [main] INFO com.okcoin.commons.okex.open.api.client.APIHttpClient - 
	Secret-Key: 
	Request(2019-08-17 17:45:40:882):
		Url: https://www.okex.com/api/spot/v3/instruments/BTC-usdt/candles?granularity=60
		Method: GET
		Headers: 
			Accept: application/json
			Content-Type: application/json; charset=UTF-8
			Cookie: locale=zh_CN
		Body: 
		preHash: 2019-08-17T21:45:40.876416900ZGET/api/spot/v3/instruments/BTC-usdt/candles?granularity=60

Disconnected from the target VM, address: '127.0.0.1:62486', transport: 'socket'

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 3 path $[0]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at com.okcoin.commons.okex.open.api.client.APIClient.executeSync(APIClient.java:71)
	at com.okcoin.commons.okex.open.api.service.spot.impl.SpotProductAPIServiceImpl.getCandles(SpotProductAPIServiceImpl.java:53)
	at com.okcoin.commons.okex.open.api.test.spot.SpotProductAPITest.getCandles(SpotProductAPITest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 34 more

Process finished with exit code -1

**Comment by mdvx** [comment]
I found a fix, I think it was config
